name: Execute when pull request on main

on:
  pull_request:
    branches: [main]

env:
  APP_NAME: expenses-api

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      app-version: ${{ steps.build-version.outputs.APP_VERSION }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Build with Maven
        run: |
         mvn -B clean package --file pom.xml
         echo "APP_VERSION=$(mvn --file pom.xml -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> "$GITHUB_OUTPUT"
        id: build-version
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: $APP_NAME
#          path: target/*.jar